{{ config(
    materialized='table',
    engine='OLAP',
    table_type='PRIMARY',
    keys=['booking_key'],
    distributed_by=['booking_key'],
    buckets=16,
    properties={'replication_num': '1'}
) }}

SELECT
    booking_key,
    booking_id,
    source_dataset,
    original_source_row_number,
    first_seen_batch_id,
    first_seen_batch_sequence,
    valid_from,
    valid_to,
    is_current,
    record_hash,
    arrival_date,
    hotel,
    country,
    market_segment,
    distribution_channel,
    reserved_room_type,
    assigned_room_type,
    customer_type,
    deposit_type,
    total_nights,
    total_guests,
    adr,
    estimated_revenue,
    realized_revenue,
    is_cancelled,
    lead_time,
    lead_time_bucket,
    stay_length_bucket,
    guest_type,
    reservation_status,
    reservation_status_date,
    has_negative_adr,
    source_file,
    loaded_at
FROM {{ ref('int_booking_metrics') }}
