INSERT INTO hotel_booking.raw_hotel_bookings (
    hotel,
    is_canceled,
    lead_time,
    arrival_date_year,
    arrival_date_month,
    arrival_date_week_number,
    arrival_date_day_of_month,
    stays_in_weekend_nights,
    stays_in_week_nights,
    adults,
    children,
    babies,
    meal,
    country,
    market_segment,
    distribution_channel,
    is_repeated_guest,
    previous_cancellations,
    previous_bookings_not_canceled,
    reserved_room_type,
    assigned_room_type,
    booking_changes,
    deposit_type,
    agent,
    company,
    days_in_waiting_list,
    customer_type,
    adr,
    required_car_parking_spaces,
    total_of_special_requests,
    reservation_status,
    reservation_status_date,
    source_file,
    loaded_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    's3://{{MINIO_BUCKET}}/{{MINIO_RAW_OBJECT_KEY}}' AS source_file,
    NOW() AS loaded_at
FROM FILES(
    'path' = 's3://{{MINIO_BUCKET}}/{{MINIO_RAW_OBJECT_KEY}}',
    'format' = 'csv',
    'csv.column_separator' = ',',
    'csv.row_delimiter' = '\n',
    'csv.enclose' = '"',
    'csv.skip_header' = '1',
    'aws.s3.endpoint' = 'http://{{MINIO_ENDPOINT}}',
    'aws.s3.access_key' = '{{MINIO_ROOT_USER}}',
    'aws.s3.secret_key' = '{{MINIO_ROOT_PASSWORD}}',
    'aws.s3.region' = 'us-east-1',
    'aws.s3.use_instance_profile' = 'false',
    'aws.s3.enable_ssl' = 'false',
    'aws.s3.enable_path_style_access' = 'true'
);
