{{ config(
    materialized='view'
) }}

SELECT
    source_dataset,
    CAST(original_source_row_number AS BIGINT) AS original_source_row_number,
    booking_key,
    batch_id,
    CAST(batch_sequence AS INT) AS batch_sequence,
    CAST(batch_effective_at AS DATETIME) AS batch_effective_at,
    CAST(batch_row_number AS BIGINT) AS batch_row_number,
    COALESCE(CAST(etl_year AS INT), YEAR(CAST(batch_effective_at AS DATETIME))) AS etl_year,
    COALESCE(CAST(etl_month AS INT), MONTH(CAST(batch_effective_at AS DATETIME))) AS etl_month,
    COALESCE(CAST(etl_day AS INT), DAYOFMONTH(CAST(batch_effective_at AS DATETIME))) AS etl_day,
    COALESCE(etl_date, DATE_FORMAT(CAST(batch_effective_at AS DATETIME), '%Y%m%d')) AS etl_date,
    COALESCE(raw_batch_sequence, LPAD(CAST(batch_sequence AS VARCHAR), 3, '0')) AS raw_batch_sequence,
    source_file_name,
    source_object_path,
    file_hash,
    SHA2(
        CONCAT_WS(
            '||',
            LOWER(TRIM(COALESCE(CAST(hotel AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(is_canceled AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(lead_time AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(arrival_date_year AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(arrival_date_month AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(arrival_date_week_number AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(arrival_date_day_of_month AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(stays_in_weekend_nights AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(stays_in_week_nights AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(adults AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(children AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(babies AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(meal AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(country AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(market_segment AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(distribution_channel AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(is_repeated_guest AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(previous_cancellations AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(previous_bookings_not_canceled AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(reserved_room_type AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(assigned_room_type AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(booking_changes AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(deposit_type AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(agent AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(company AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(days_in_waiting_list AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(customer_type AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(adr AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(required_car_parking_spaces AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(total_of_special_requests AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(reservation_status AS VARCHAR), ''))),
            LOWER(TRIM(COALESCE(CAST(reservation_status_date AS VARCHAR), '')))
        ),
        256
    ) AS record_hash,
    CAST(ingested_at AS DATETIME) AS ingested_at,
    row_ingestion_id,
    synthetic_operation,
    hotel,
    is_canceled,
    lead_time,
    arrival_date_year,
    arrival_date_month,
    arrival_date_week_number,
    arrival_date_day_of_month,
    stays_in_weekend_nights,
    stays_in_week_nights,
    adults,
    children,
    babies,
    meal,
    country,
    market_segment,
    distribution_channel,
    is_repeated_guest,
    previous_cancellations,
    previous_bookings_not_canceled,
    reserved_room_type,
    assigned_room_type,
    booking_changes,
    deposit_type,
    agent,
    company,
    days_in_waiting_list,
    customer_type,
    adr,
    required_car_parking_spaces,
    total_of_special_requests,
    reservation_status,
    reservation_status_date
FROM `{{ env_var('ICEBERG_CATALOG_NAME', 'iceberg_catalog') }}`.`{{ env_var('ICEBERG_DATABASE', 'hotel_booking_lakehouse') }}`.`{{ env_var('ICEBERG_RAW_HISTORY_TABLE', 'raw_hotel_bookings_history') }}`
